#include "bharatopt/cuda_backend.hpp"
#include <cuda_runtime.h>
namespace bharatopt::cuda_backend {
__global__ void kspmv(int rows,const double*v,const int*c,const int*r,const double*x,double*y){int i=blockIdx.x*blockDim.x+threadIdx.x;if(i>=rows)return;double s=0;for(int k=r[i];k<r[i+1];k++)s+=v[k]*x[c[k]];y[i]=s;}
__global__ void kproj(int n,double*x,const double*lo,const double*hi){int i=blockIdx.x*blockDim.x+threadIdx.x;if(i<n)x[i]=fmin(fmax(x[i],lo[i]),hi[i]);}
bool cuda_available(){int n=0;return cudaGetDeviceCount(&n)==cudaSuccess&&n>0;}
std::string cuda_device_name(){if(!cuda_available())return "none";cudaDeviceProp p{};if(cudaGetDeviceProperties(&p,0)!=cudaSuccess)return "unknown";return p.name;}
bool spmv(const SparseMatrixCSR&A,const std::vector<double>&x,std::vector<double>&y){if(!cuda_available()||x.size()!=A.cols)return false;double*dV=nullptr,*dX=nullptr,*dY=nullptr;int*dC=nullptr,*dR=nullptr;auto cl=[&](){if(dV)cudaFree(dV);if(dX)cudaFree(dX);if(dY)cudaFree(dY);if(dC)cudaFree(dC);if(dR)cudaFree(dR);};if(cudaMalloc(&dV,A.values.size()*sizeof(double))!=0)return false;if(cudaMalloc(&dC,A.col_index.size()*sizeof(int))!=0){cl();return false;}if(cudaMalloc(&dR,A.row_ptr.size()*sizeof(int))!=0){cl();return false;}if(cudaMalloc(&dX,x.size()*sizeof(double))!=0){cl();return false;}if(cudaMalloc(&dY,A.rows*sizeof(double))!=0){cl();return false;}cudaMemcpy(dV,A.values.data(),A.values.size()*sizeof(double),cudaMemcpyHostToDevice);cudaMemcpy(dC,A.col_index.data(),A.col_index.size()*sizeof(int),cudaMemcpyHostToDevice);cudaMemcpy(dR,A.row_ptr.data(),A.row_ptr.size()*sizeof(int),cudaMemcpyHostToDevice);cudaMemcpy(dX,x.data(),x.size()*sizeof(double),cudaMemcpyHostToDevice);kspmv<<<(A.rows+255)/256,256>>>((int)A.rows,dV,dC,dR,dX,dY);if(cudaDeviceSynchronize()!=cudaSuccess){cl();return false;}y.resize(A.rows);cudaMemcpy(y.data(),dY,A.rows*sizeof(double),cudaMemcpyDeviceToHost);cl();return true;}
bool project_box(std::vector<double>&x,const std::vector<double>&lo,const std::vector<double>&hi){if(!cuda_available()||x.size()!=lo.size()||x.size()!=hi.size())return false;size_t n=x.size();double*dX=nullptr,*dL=nullptr,*dH=nullptr;auto cl=[&](){if(dX)cudaFree(dX);if(dL)cudaFree(dL);if(dH)cudaFree(dH);};if(cudaMalloc(&dX,n*sizeof(double))!=0)return false;if(cudaMalloc(&dL,n*sizeof(double))!=0){cl();return false;}if(cudaMalloc(&dH,n*sizeof(double))!=0){cl();return false;}cudaMemcpy(dX,x.data(),n*sizeof(double),cudaMemcpyHostToDevice);cudaMemcpy(dL,lo.data(),n*sizeof(double),cudaMemcpyHostToDevice);cudaMemcpy(dH,hi.data(),n*sizeof(double),cudaMemcpyHostToDevice);kproj<<<(n+255)/256,256>>>((int)n,dX,dL,dH);if(cudaDeviceSynchronize()!=cudaSuccess){cl();return false;}cudaMemcpy(x.data(),dX,n*sizeof(double),cudaMemcpyDeviceToHost);cl();return true;}
}